;; a)
(or (supervisor ?middle-manager (Bitdiddle Ben))
    (supervisor ?person ?middle-manager))
;; b)
(and (salary (Bitdiddle Ben) ?salary-ben)
     (lisp-value < ?salary ?salary-ben))
;; c)
(and (supervisor ?person ?manager)
     (not (job ?person (computer . ?job))))
